apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  RabbitMq__Host: "rabbitmq"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  Loki__Url: "http://loki:3100"
