apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis 6379; do sleep 2; done']
        - name: wait-for-rabbit
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do sleep 2; done']
      containers:
        - name: notifications-api
          image: ghcr.io/reinaldogez/fcg-notifications:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notifications-config
            - secretRef:
                name: notifications-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
