apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres-catalog 5432; do sleep 2; done']
        - name: wait-for-rabbit
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do sleep 2; done']
      containers:
        - name: catalog-api
          image: ghcr.io/reinaldogez/fcg-catalog:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-config
            - secretRef:
                name: catalog-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
